import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding universities and programs...')

  // Clear existing data
  await prisma.programs.deleteMany()
  await prisma.universities.deleteMany()

  // Create Universities
  const universities = [
    {
      name: 'Harvard University',
      slug: 'harvard-university',
      country: 'United States',
      city: 'Cambridge',
      state: 'Massachusetts',
      address: 'Massachusetts Hall, Cambridge, MA 02138',
      postal_code: '02138',
      logo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Harvard_University_coat_of_arms.svg/200px-Harvard_University_coat_of_arms.svg.png',
      banner_url: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200',
      images: [
        'https://images.unsplash.com/photo-1562774053-701939374585?w=800',
        'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800'
      ],
      website: 'https://www.harvard.edu',
      email: 'admissions@harvard.edu',
      phone: '+1 (617) 495-1000',
      description: 'Harvard University is a private Ivy League research university in Cambridge, Massachusetts.',
      about: '<p>Harvard University is devoted to excellence in teaching, learning, and research, and to developing leaders who make a difference globally. Founded in 1636, Harvard is the oldest institution of higher education in the United States.</p><p>With twelve degree-granting schools in addition to the Radcliffe Institute for Advanced Study, Harvard offers unparalleled resources to its students.</p>',
      facilities: ['Library', 'Research Labs', 'Sports Complex', 'Medical Center', 'Museums', 'Student Housing', 'Dining Halls'],
      type: 'Private',
      established_year: 1636,
      accreditation: 'New England Commission of Higher Education',
      ranking_national: 1,
      ranking_world: 1,
      student_count: 23000,
      international_students: 5600,
      acceptance_rate: 3.2,
      avg_tuition_fee: 54269,
      currency: 'USD',
      campus_size: '209 acres',
      departments: ['Arts & Sciences', 'Engineering', 'Business', 'Law', 'Medicine', 'Education', 'Government'],
      notable_alumni: ['Barack Obama', 'Mark Zuckerberg', 'Bill Gates', 'Natalie Portman'],
      partnerships: ['MIT', 'Cambridge University', 'Oxford University'],
      admission_requirements: 'SAT/ACT scores, High school transcript, Letters of recommendation, Essays, Interview',
      application_deadline: 'January 1',
      language_requirement: 'TOEFL 100 or IELTS 7.5',
      tags: ['ivy league', 'research university', 'prestigious'],
      meta_title: 'Harvard University - Top Ranked University in USA',
      meta_description: 'Apply to Harvard University, the #1 ranked university in the world. Explore programs, admissions, and scholarships.',
      is_featured: true,
      is_published: true,
    },
    {
      name: 'Stanford University',
      slug: 'stanford-university',
      country: 'United States',
      city: 'Stanford',
      state: 'California',
      address: '450 Serra Mall, Stanford, CA 94305',
      postal_code: '94305',
      logo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Seal_of_Leland_Stanford_Junior_University.svg/200px-Seal_of_Leland_Stanford_Junior_University.svg.png',
      banner_url: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200',
      images: [
        'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800'
      ],
      website: 'https://www.stanford.edu',
      email: 'admission@stanford.edu',
      phone: '+1 (650) 723-2300',
      description: 'Stanford University is a private research university in Stanford, California, known for its entrepreneurial character.',
      about: '<p>Stanford University has been one of the world\'s leading research and teaching institutions since its founding in 1885. Located in the heart of Silicon Valley, Stanford is known for its entrepreneurial spirit and close ties to the tech industry.</p>',
      facilities: ['Innovation Labs', 'Libraries', 'Recreation Centers', 'Medical Facilities', 'Art Museums'],
      type: 'Private',
      established_year: 1885,
      accreditation: 'WASC Senior College and University Commission',
      ranking_national: 3,
      ranking_world: 2,
      student_count: 17249,
      international_students: 3879,
      acceptance_rate: 3.9,
      avg_tuition_fee: 57693,
      currency: 'USD',
      campus_size: '8180 acres',
      departments: ['Engineering', 'Business', 'Humanities', 'Medicine', 'Law', 'Earth Sciences'],
      notable_alumni: ['Larry Page', 'Sergey Brin', 'Elon Musk', 'Reed Hastings'],
      partnerships: ['Google', 'Apple', 'Tesla', 'Berkeley'],
      admission_requirements: 'SAT/ACT, Transcripts, Recommendations, Essays',
      application_deadline: 'January 5',
      language_requirement: 'TOEFL 100 or IELTS 7.0',
      tags: ['silicon valley', 'innovation', 'technology'],
      meta_title: 'Stanford University - Premier California University',
      meta_description: 'Discover Stanford University programs and admissions in the heart of Silicon Valley.',
      is_featured: true,
      is_published: true,
    },
    {
      name: 'University of Toronto',
      slug: 'university-of-toronto',
      country: 'Canada',
      city: 'Toronto',
      state: 'Ontario',
      address: '27 King\'s College Circle, Toronto, ON M5S 1A1',
      postal_code: 'M5S 1A1',
      logo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Coat_of_arms_of_the_University_of_Toronto.svg/200px-Coat_of_arms_of_the_University_of_Toronto.svg.png',
      banner_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200',
      images: [
        'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800'
      ],
      website: 'https://www.utoronto.ca',
      email: 'admissions@utoronto.ca',
      phone: '+1 (416) 978-2011',
      description: 'The University of Toronto is a public research university and Canada\'s top-ranked institution.',
      about: '<p>The University of Toronto is a globally top-ranked public research university in Toronto, Ontario, Canada. Founded in 1827, U of T is Canada\'s leading institution of learning, discovery and knowledge creation.</p>',
      facilities: ['Research Centers', 'Libraries', 'Athletic Centers', 'Student Services', 'Hospitals'],
      type: 'Public',
      established_year: 1827,
      accreditation: 'Ministry of Training, Colleges and Universities',
      ranking_national: 1,
      ranking_world: 18,
      student_count: 93000,
      international_students: 23000,
      acceptance_rate: 43.0,
      avg_tuition_fee: 45690,
      currency: 'CAD',
      campus_size: '71 hectares',
      departments: ['Arts & Science', 'Engineering', 'Medicine', 'Law', 'Business', 'Nursing'],
      notable_alumni: ['William Lyon Mackenzie King', 'Lester B. Pearson', 'Michael Ondaatje'],
      partnerships: ['MIT', 'Oxford', 'Cambridge'],
      admission_requirements: 'High school diploma, English proficiency, Prerequisites by program',
      application_deadline: 'January 15',
      language_requirement: 'IELTS 6.5 or TOEFL 100',
      tags: ['canada', 'research', 'diverse programs'],
      meta_title: 'University of Toronto - Top Canadian University',
      meta_description: 'Study at Canada\'s #1 university. Explore programs at University of Toronto.',
      is_featured: true,
      is_published: true,
    },
    {
      name: 'University of British Columbia',
      slug: 'university-of-british-columbia',
      country: 'Canada',
      city: 'Vancouver',
      state: 'British Columbia',
      address: '2329 West Mall, Vancouver, BC V6T 1Z4',
      postal_code: 'V6T 1Z4',
      website: 'https://www.ubc.ca',
      email: 'admissions@ubc.ca',
      phone: '+1 (604) 822-2211',
      description: 'UBC is a global centre for research and teaching, consistently ranked among the top public universities in the world.',
      about: '<p>The University of British Columbia is a global centre for research and teaching, consistently ranked among the top 40 universities in the world. UBC embraces innovation and transforms ideas into action.</p>',
      facilities: ['Research Labs', 'Libraries', 'Recreation Facilities', 'Museums', 'Botanical Garden'],
      type: 'Public',
      established_year: 1908,
      accreditation: 'Ministry of Advanced Education',
      ranking_national: 2,
      ranking_world: 34,
      student_count: 66000,
      international_students: 17000,
      acceptance_rate: 52.0,
      avg_tuition_fee: 38000,
      currency: 'CAD',
      campus_size: '402 hectares',
      departments: ['Applied Science', 'Arts', 'Commerce', 'Science', 'Forestry', 'Land and Food Systems'],
      notable_alumni: ['Justin Trudeau', 'Kim Campbell'],
      partnerships: ['Harvard', 'Yale', 'Princeton'],
      admission_requirements: 'Academic records, English proficiency, Personal profile',
      application_deadline: 'January 15',
      language_requirement: 'IELTS 6.5 or TOEFL 90',
      tags: ['research', 'beautiful campus', 'diverse'],
      meta_title: 'University of British Columbia - Study in Vancouver',
      meta_description: 'Explore UBC programs in Vancouver, one of the world\'s most beautiful campuses.',
      is_featured: true,
      is_published: true,
    },
    {
      name: 'University of Melbourne',
      slug: 'university-of-melbourne',
      country: 'Australia',
      city: 'Melbourne',
      state: 'Victoria',
      address: 'Parkville VIC 3010',
      postal_code: '3010',
      website: 'https://www.unimelb.edu.au',
      email: 'admissions@unimelb.edu.au',
      phone: '+61 3 9035 5511',
      description: 'The University of Melbourne is Australia\'s leading university and ranks among the finest universities in the world.',
      about: '<p>Since 1853, the University of Melbourne has been a leader in teaching and research. We offer a distinctive Melbourne experience that attracts the best students from around the world.</p>',
      facilities: ['State-of-art Labs', 'Libraries', 'Sports Facilities', 'Student Accommodation', 'Medical Center'],
      type: 'Public',
      established_year: 1853,
      accreditation: 'Tertiary Education Quality and Standards Agency',
      ranking_national: 1,
      ranking_world: 14,
      student_count: 51000,
      international_students: 18000,
      acceptance_rate: 70.0,
      avg_tuition_fee: 44000,
      currency: 'AUD',
      campus_size: '20 hectares',
      departments: ['Arts', 'Science', 'Engineering', 'Medicine', 'Business', 'Law'],
      notable_alumni: ['Julia Gillard', 'Germaine Greer'],
      partnerships: ['Cambridge', 'Yale', 'UC Berkeley'],
      admission_requirements: 'Academic transcripts, English proficiency, Personal statement',
      application_deadline: 'October 31',
      language_requirement: 'IELTS 6.5 or TOEFL 79',
      tags: ['group of eight', 'research intensive', 'international'],
      meta_title: 'University of Melbourne - Australia\'s #1 University',
      meta_description: 'Study at the University of Melbourne, consistently ranked as Australia\'s best university.',
      is_featured: true,
      is_published: true,
    }
  ]

  console.log('Creating universities...')
  const createdUniversities = []
  for (const uni of universities) {
    const created = await prisma.universities.create({ data: uni })
    createdUniversities.push(created)
    console.log(`✓ Created: ${created.name}`)
  }

  // Create Programs
  console.log('\nCreating programs...')

  const programs = [
    // Harvard Programs
    {
      university_id: createdUniversities[0].id,
      name: 'Bachelor of Computer Science',
      slug: 'bachelor-computer-science',
      degree_type: 'Bachelor',
      discipline: 'Computer Science',
      specialization: 'Artificial Intelligence',
      duration_years: 4,
      duration_months: 48,
      intake_months: ['September', 'January'],
      featured_image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
      images: ['https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800'],
      description: 'A comprehensive computer science program focusing on algorithms, data structures, and AI.',
      overview: '<p>This program provides a strong foundation in computer science with opportunities to specialize in artificial intelligence, machine learning, and software engineering.</p>',
      curriculum: '<ul><li>Data Structures and Algorithms</li><li>Machine Learning</li><li>Artificial Intelligence</li><li>Database Systems</li><li>Software Engineering</li></ul>',
      career_opportunities: '<p>Graduates work as software engineers, data scientists, AI researchers, and technology consultants at leading companies worldwide.</p>',
      tuition_fee: 54269,
      application_fee: 75,
      currency: 'USD',
      scholarship_available: true,
      scholarship_details: 'Merit-based scholarships available up to $40,000 per year',
      hostel_available: true,
      hostel_fee: 15000,
      living_cost_min: 18000,
      living_cost_max: 25000,
      total_seats: 200,
      international_seats: 50,
      language_requirement: 'TOEFL 100 or IELTS 7.5',
      min_gpa: 3.8,
      entrance_exam: 'SAT or ACT',
      work_permit: true,
      pr_pathway: false,
      internship_included: true,
      online_available: false,
      requirements: 'Strong background in mathematics and science required',
      documents_needed: ['Transcripts', 'SAT Scores', 'Essays', 'Recommendations', 'Resume'],
      job_prospects: ['Software Engineer', 'Data Scientist', 'AI Researcher', 'Tech Consultant'],
      average_salary: 120000,
      tags: ['computer science', 'ai', 'technology'],
      meta_title: 'Bachelor of Computer Science - Harvard University',
      meta_description: 'Study Computer Science with AI specialization at Harvard University.',
      is_featured: true,
      is_published: true,
    },
    {
      university_id: createdUniversities[0].id,
      name: 'Master of Business Administration (MBA)',
      slug: 'master-business-administration',
      degree_type: 'Master',
      discipline: 'Business',
      duration_years: 2,
      duration_months: 24,
      intake_months: ['September'],
      description: 'Harvard Business School MBA program - world\'s most prestigious business degree.',
      overview: '<p>The Harvard MBA program is designed to educate leaders who make a difference in the world.</p>',
      curriculum: '<ul><li>Strategic Management</li><li>Finance</li><li>Marketing</li><li>Leadership</li><li>Entrepreneurship</li></ul>',
      career_opportunities: '<p>MBA graduates become CEOs, consultants, entrepreneurs, and business leaders globally.</p>',
      tuition_fee: 73440,
      application_fee: 250,
      currency: 'USD',
      scholarship_available: true,
      scholarship_details: 'Need-based financial aid available',
      hostel_available: true,
      hostel_fee: 18000,
      living_cost_min: 20000,
      living_cost_max: 30000,
      total_seats: 900,
      international_seats: 350,
      language_requirement: 'TOEFL 109',
      min_gpa: 3.7,
      entrance_exam: 'GMAT or GRE',
      work_permit: true,
      pr_pathway: false,
      internship_included: true,
      online_available: false,
      requirements: 'Work experience required (average 5 years)',
      documents_needed: ['GMAT/GRE', 'Essays', 'Resume', 'Recommendations', 'Transcripts'],
      job_prospects: ['Management Consultant', 'Investment Banker', 'CEO', 'Entrepreneur'],
      average_salary: 180000,
      tags: ['mba', 'business', 'leadership'],
      is_featured: true,
      is_published: true,
    },
    // Stanford Programs
    {
      university_id: createdUniversities[1].id,
      name: 'Bachelor of Engineering',
      slug: 'bachelor-engineering',
      degree_type: 'Bachelor',
      discipline: 'Engineering',
      specialization: 'Electrical Engineering',
      duration_years: 4,
      duration_months: 48,
      intake_months: ['September'],
      description: 'Stanford Engineering offers rigorous programs in electrical, mechanical, and computer engineering.',
      overview: '<p>Study engineering at one of the world\'s top institutions located in Silicon Valley.</p>',
      curriculum: '<ul><li>Circuit Theory</li><li>Digital Systems</li><li>Signal Processing</li><li>Control Systems</li><li>Power Electronics</li></ul>',
      career_opportunities: '<p>Work at leading tech companies in Silicon Valley and beyond.</p>',
      tuition_fee: 57693,
      application_fee: 90,
      currency: 'USD',
      scholarship_available: true,
      scholarship_details: 'Need-blind admissions with full financial aid',
      hostel_available: true,
      hostel_fee: 16000,
      living_cost_min: 19000,
      living_cost_max: 26000,
      total_seats: 300,
      international_seats: 80,
      language_requirement: 'TOEFL 100',
      min_gpa: 3.9,
      entrance_exam: 'SAT Subject Tests recommended',
      work_permit: true,
      pr_pathway: true,
      internship_included: true,
      online_available: false,
      requirements: 'Strong math and physics background',
      documents_needed: ['Transcripts', 'SAT', 'Essays', 'Recommendations'],
      job_prospects: ['Hardware Engineer', 'Software Engineer', 'Systems Architect', 'Research Scientist'],
      average_salary: 115000,
      tags: ['engineering', 'technology', 'silicon valley'],
      is_featured: true,
      is_published: true,
    },
    // University of Toronto Programs
    {
      university_id: createdUniversities[2].id,
      name: 'Bachelor of Science in Computer Science',
      slug: 'bachelor-science-computer-science',
      degree_type: 'Bachelor',
      discipline: 'Computer Science',
      duration_years: 4,
      duration_months: 48,
      intake_months: ['September', 'January', 'May'],
      description: 'One of Canada\'s premier computer science programs with co-op opportunities.',
      overview: '<p>U of T Computer Science offers world-class education in AI, machine learning, and software engineering.</p>',
      curriculum: '<ul><li>Programming Fundamentals</li><li>Data Structures</li><li>Algorithms</li><li>Machine Learning</li><li>Computer Networks</li></ul>',
      career_opportunities: '<p>Strong co-op program with placements at top Canadian and international tech companies.</p>',
      tuition_fee: 58160,
      application_fee: 156,
      currency: 'CAD',
      scholarship_available: true,
      scholarship_details: 'Entrance scholarships up to $7,500',
      hostel_available: true,
      hostel_fee: 14000,
      living_cost_min: 15000,
      living_cost_max: 18000,
      total_seats: 400,
      international_seats: 120,
      language_requirement: 'IELTS 6.5 (no band below 6.0)',
      min_gpa: 3.5,
      work_permit: true,
      pr_pathway: true,
      internship_included: true,
      online_available: false,
      requirements: 'High school diploma with strong math and science grades',
      documents_needed: ['Transcripts', 'English Test', 'Personal Profile', 'Supplementary Application'],
      job_prospects: ['Software Developer', 'Data Analyst', 'AI Engineer', 'Systems Administrator'],
      average_salary: 85000,
      tags: ['computer science', 'co-op', 'canada'],
      is_featured: true,
      is_published: true,
    },
    {
      university_id: createdUniversities[2].id,
      name: 'Master of Engineering',
      slug: 'master-engineering',
      degree_type: 'Master',
      discipline: 'Engineering',
      specialization: 'Civil Engineering',
      duration_years: 2,
      duration_months: 24,
      intake_months: ['September', 'January'],
      description: 'Advanced engineering program with focus on sustainable infrastructure and design.',
      overview: '<p>The MEng program prepares students for leadership roles in engineering practice and research.</p>',
      curriculum: '<ul><li>Structural Analysis</li><li>Sustainable Design</li><li>Project Management</li><li>Transportation Engineering</li></ul>',
      career_opportunities: '<p>Graduates work on major infrastructure projects worldwide.</p>',
      tuition_fee: 32000,
      application_fee: 125,
      currency: 'CAD',
      scholarship_available: true,
      scholarship_details: 'Research assistantships and teaching fellowships available',
      hostel_available: true,
      hostel_fee: 12000,
      living_cost_min: 15000,
      living_cost_max: 20000,
      total_seats: 150,
      international_seats: 75,
      language_requirement: 'IELTS 7.0',
      min_gpa: 3.3,
      entrance_exam: 'GRE recommended',
      work_permit: true,
      pr_pathway: true,
      internship_included: false,
      online_available: false,
      requirements: 'Bachelor degree in Engineering or related field',
      documents_needed: ['Transcripts', 'Resume', 'Statement of Purpose', 'References'],
      job_prospects: ['Civil Engineer', 'Project Manager', 'Structural Engineer', 'Consultant'],
      average_salary: 95000,
      tags: ['engineering', 'civil', 'infrastructure'],
      is_featured: false,
      is_published: true,
    },
    // UBC Programs
    {
      university_id: createdUniversities[3].id,
      name: 'Bachelor of Commerce',
      slug: 'bachelor-commerce',
      degree_type: 'Bachelor',
      discipline: 'Business',
      duration_years: 4,
      duration_months: 48,
      intake_months: ['September'],
      description: 'UBC Sauder School of Business offers Canada\'s top undergraduate business program.',
      overview: '<p>Develop business acumen through case studies, team projects, and international exchanges.</p>',
      curriculum: '<ul><li>Accounting</li><li>Finance</li><li>Marketing</li><li>Strategy</li><li>Entrepreneurship</li></ul>',
      career_opportunities: '<p>Access to Vancouver\'s thriving business community and global career opportunities.</p>',
      tuition_fee: 42802,
      application_fee: 118,
      currency: 'CAD',
      scholarship_available: true,
      scholarship_details: 'Outstanding International Student Award up to $10,000',
      hostel_available: true,
      hostel_fee: 13500,
      living_cost_min: 14000,
      living_cost_max: 18000,
      total_seats: 250,
      international_seats: 60,
      language_requirement: 'IELTS 6.5',
      min_gpa: 3.6,
      work_permit: true,
      pr_pathway: true,
      internship_included: true,
      online_available: false,
      requirements: 'Strong academic record and personal profile',
      documents_needed: ['Transcripts', 'Personal Profile', 'English Test'],
      job_prospects: ['Business Analyst', 'Marketing Manager', 'Financial Analyst', 'Consultant'],
      average_salary: 75000,
      tags: ['business', 'commerce', 'vancouver'],
      is_featured: true,
      is_published: true,
    },
    // Melbourne Programs
    {
      university_id: createdUniversities[4].id,
      name: 'Bachelor of Science',
      slug: 'bachelor-science',
      degree_type: 'Bachelor',
      discipline: 'Science',
      specialization: 'Biotechnology',
      duration_years: 3,
      duration_months: 36,
      intake_months: ['February', 'July'],
      description: 'Explore the frontiers of biotechnology at Australia\'s leading university.',
      overview: '<p>Gain hands-on experience in cutting-edge biotechnology research and applications.</p>',
      curriculum: '<ul><li>Molecular Biology</li><li>Genetics</li><li>Biochemistry</li><li>Microbiology</li><li>Bioethics</li></ul>',
      career_opportunities: '<p>Work in pharmaceutical companies, research institutes, and healthcare organizations.</p>',
      tuition_fee: 44000,
      application_fee: 100,
      currency: 'AUD',
      scholarship_available: true,
      scholarship_details: 'Melbourne International Undergraduate Scholarship',
      hostel_available: true,
      hostel_fee: 16000,
      living_cost_min: 20000,
      living_cost_max: 27000,
      total_seats: 180,
      international_seats: 70,
      language_requirement: 'IELTS 6.5',
      min_gpa: 3.4,
      work_permit: true,
      pr_pathway: true,
      internship_included: true,
      online_available: false,
      requirements: 'Strong background in biology and chemistry',
      documents_needed: ['Academic Transcripts', 'English Test', 'Personal Statement'],
      job_prospects: ['Biotechnologist', 'Research Scientist', 'Quality Analyst', 'Lab Manager'],
      average_salary: 70000,
      tags: ['biotechnology', 'science', 'australia'],
      is_featured: false,
      is_published: true,
    },
  ]

  for (const program of programs) {
    const created = await prisma.programs.create({ data: program })
    console.log(`✓ Created: ${created.name}`)
  }

  console.log('\n✅ Seeding completed successfully!')
  console.log(`📊 Created ${createdUniversities.length} universities`)
  console.log(`📚 Created ${programs.length} programs`)
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
